### PR TITLE
rebased PR#8

### PR DESCRIPTION
**Pull request by boneskull**
this is PR #8 but rebased.

### CODE REVIEW

**Comment by boneskull** [comment]
cc @bauer-san

**Comment by tedder** [comment]
hey @ladyada @iworkinpixels is there any chance this could be merged? it'd be nice to have this library updated for modern Arduinos.

**Comment by tedder** [comment]
actually @boneskull it should really be `else` instead of `elsif 8266`.. at least according to the sampling of headers I just did.

**Comment by ladyada** [comment]
oof this code is so ancient, could you change _delay_ms(1); to delay(1); then it should Just Work on everything!

**Comment by ladyada** [comment]
hand fixed

**Comment by boneskull** [comment]
lol can you believe I forgot about this one? thanks 🙂

**Comment by ladyada** [comment]
thank u :)

**Pull request closed without merging**
